### ISSUE TITLE
🐛 [BUG] - certificate.verify() does not verify dapp-kit-certificates

### ISSUE THREAD

**Issue by ifavo** [vechain/vechain-sdk-js#833]
### Description

I am verifying a certificate generated during wallet connection with dApp-Kit-UI with `@vechain/sdk-core`'s `certificate.verify()`.

The verification fails with signature does not correspond to signer. It might be related to #809

### Reproduction URL

https://stackblitz.com/edit/stackblitz-starters-mtgkxg?file=pages%2Fapi%2Fverify.ts

### Reproduction steps

1. encode the certificate provided by dApp-Kit: `const encodedCertificate = btoa(JSON.stringify(connectionCertificate));`
2. decode and verify using:

```js
const decodedCertificate = JSON.parse(atob(encodedCertificate));
certificate.verify(decodedCertificate);
```

It fails with:

```
Method 'Assertion on verify' failed.\n-Reason: 'Verification failed: Signature does not correspond to the signer's public key.'
```

I would expect this verification to succeed.

**Comment by fabiorigam** [comment]
Fixed here https://github.com/vechain/vechain-sdk-js/issues/809

**Comment by ifavo** [comment]
@fabiorigam It is not fixed for me, the issue remains after updating to beta-10, here is an example snippet with a certificate I signed with VeWorld:


```js
const SDK = require('@vechain/sdk-core');
const Thor = require('thor-devkit');

const myCert = {
  purpose: 'identification',
  payload: {
    type: 'text',
    content:
      'The following dApp would like to see your public address: https://stackblitzstartersmtgkxg-tcrt--3000--12d46890.local-credentialless.webcontainer.io',
  },
  signature:
    '0x69b0d95df24db73b30eb109e4dffab955d586edf919001be466ceceed6168d4372715b6f8fe489214e46f24d8252fba587da6fc241a33599109d80e328267fc300',
  signer: '0x105199a26b10e55300cb71b46c5b5e867b7df427',
  domain:
    'stackblitzstartersmtgkxg-tcrt--3000--12d46890.local-credentialless.webcontainer.io',
  timestamp: 1717150342,
};

console.log('Verify with thor-devkit:');
try {
  Thor.Certificate.verify(myCert);
  console.log('=> success');
} catch {
  console.log('=> error');
}

console.log('Verify with @vechain/sdk-core:');
try {
  SDK.certificate.verify(myCert);
  console.log('=> success');
} catch {
  console.log('=> error');
}
```

https://stackblitz.com/edit/stackblitz-starters-wokbsl?file=index.js

**Comment by ifavo** [comment]
Also tested with the latest beta-12 version. Still failing for me. Would be great if you could have another look at it, with the previous example.

**Comment by lucanicoladebiasi** [comment]
Fixed in https://github.com/vechain/vechain-sdk-js/pull/985.

**Comment by ifavo** [comment]
I can confirm that with beta-17 it works, thanks a lot 🙌
